### PR TITLE
about section with placeholder graphics

### LINKED ISSUE #13: Create About section

### PR DESCRIPTION
**Pull request by gordonpn**
# Screenshots

## iPad

Localhost - Full - iPad - 2020-2-9 at 10 27 13 AM

## iPhone X

Localhost - Full - iPhone X - 2020-2-9 at 10 27 06 AM

## Laptop with HiDPI

Localhost - Full - Laptop with HiDPI screen - 2020-2-9 at 10 27 24 AM

closes #13

### CODE REVIEW

**Comment by sttic** [comment]
Amazing! :heart: 

Some minor nitpicks :stuck_out_tongue: :

1. Maybe there could be a tiny bit of more space under the "Annual Software Engineering Conference" header, especially on smallest mobile?
2. I'm not sure but it looks like the cards aren't horizontally centered by a really small amount when the screen width is constraining the card. It's barely noticeable so dw about it if a fix isn't obvious

In the screenshot I'm selecting the div that has all the cards in it and they go past its right edge. Maybe the `max-width: 100%` isn't behaving as expected?

image

Also I noticed a52051162167d688bb3d1d5c47bd7213039db4bd , good thinking! If you want to, we can cherry pick that into master/splash page when this gets merged :smile:

**Comment by gordonpn** [comment]
> Maybe there could be a tiny bit of more space under the "Annual Software Engineering Conference" header, especially on smallest mobile?

Oh yes, definitely!

> I'm not sure but it looks like the cards aren't horizontally centered by a really small amount when the screen width is constraining the card. It's barely noticeable so dw about it if a fix isn't obvious
> In the screenshot I'm selecting the div that has all the cards in it and they go past its right edge. Maybe the max-width: 100% isn't behaving as expected?

I didn't even notice, thanks! I'll check it out! 

> Also I noticed a520511 , good thinking! If you want to, we can cherry pick that into master/splash page when this gets merged 😄

Yes!

**Comment by gordonpn** [comment]
Is it sketch if I reduced the `max-width` to 98% and it looks centred to me?

image

What do you think?

**Comment by sttic** [comment]
> Is it sketch if I reduced the `max-width` to 98% and it looks centred to me?

Tbh it's a bit sketchy but if it works, it works :shrug: :joy: 

I'd check with the common browsers to see if it's showing up ok for them

**Comment by gordonpn** [comment]
I just checked with Firefox and Safari, and it looks good to me!

**Review by sttic — APPROVED** [review]
Great work!

**Pull request merged**
