### PR TITLE
feat: Chakra UI migration

### PR DESCRIPTION
**Pull request by gordonpn**
In this PR:
- A very basic layout for the schedule page
- Migration from Chakra v0.8 to v1!

~Notes:~
~- Although I was able to fix a lot of the visual changes due to the migration, I wasn't able to fix these two:~
  ~- The "send" icon for the email subscriptions at the bottom of the page, it used to be a sort of oval. Now it is a circle.~
  ~- Only keeping one FAQ item open at a time, now one in each column can be opened, but only one will have "focus"~

This PR would allow us to use the [Table component](https://chakra-ui.com/docs/data-display/table) to display the schedule!

### CODE REVIEW

**Comment by sttic** [comment]
In addition to your notes, I see that the registration pages with Typeform integration are hidden (they became 0 height?) and FAQ items can't be closed directly by clicking on the header again.

Do you want to merge this to staging and we can gradually fix issues in separate PRs or keep this open and do it here?

> This PR would allow us to use the Table component to display the schedule!

Amazing!!

**Comment by gordonpn** [comment]
> In addition to your notes, I see that the registration pages with Typeform integration are hidden (they became 0 height?) and FAQ items can't be closed directly by clicking on the header again.
> 
> Do you want to merge this to staging and we can gradually fix issues in separate PRs or keep this open and do it here?
> 
> > This PR would allow us to use the Table component to display the schedule!
> 
> Amazing!!

Ouf, I'm gonna take a look at the bug with the registration form. I'll switch this PR to draft for now!

**Review by sttic — APPROVED** [review]
LGTM :rocket: Thank you Gordon for the big migration effort! I saw those detailed commit messages haha

Also that new table in the WIP schedule page is looking cool so far :smile:

**Comment by gordonpn** [comment]
> LGTM 🚀 Thank you Gordon for the big migration effort! I saw those detailed commit messages haha
> 
> Also that new table in the WIP schedule page is looking cool so far 😄

Thank you for your help!

I think we should let this one sit in staging until we're done with the schedule page 😂

**Pull request merged**
