### PR TITLE
Update email listing input to only have prompt in the input placeholder

### LINKED ISSUE #25: Rearrange/modify splash page mailing list and sponsor link items
> Would it make sense to put "Join our email list" and the input box on the same line? And move the "Interested in sponsoring?" text to it's own line in Desktop?

> "Join our email listing" => "Join our email list" or "Join our mailing list"

https://cusec-team.slack.com/archives/C03KB4HCN/p1599061048000400?thread_ts=1598997168.005300&cid=C03KB4HCN

Currently:

image

---

It might be tricky finding a layout on desktop that makes the "Join our mailing list" message association clear while also not taking up too many lines.

### PR DESCRIPTION
**Pull request by sttic**
Resolves #25 

image

image

### CODE REVIEW

**Comment by gordonpn** [comment]
"Enter your email address to stay connected" seems a bit long, what do you think of "Stay connected by email"?

It doesn't say "email address" specifically, but "by email" insinuates it's with an email address... LOL

If they do enter something different from an email address, then there is a toast from the top that tells them the email is invalid right?

**Comment by sttic** [comment]
> "Enter your email address to stay connected" seems a bit long, what do you think of "Stay connected by email"?

Yeah I agree, it's rather long. I like your "Stay connected by email" a lot more!

> If they do enter something different from an email address, then there is a toast from the top that tells them the email is invalid right?

It shows that it's invalid with the red and tells them to "Please enter a valid email." While we're at it, I think the toast might as well be more specific and tell them to enter their "email address" instead of just "email" (no need to insinuate it when there's enough room in the toast :joy: )

image

**Comment by gordonpn** [comment]
> While we're at it, I think the toast might as well be more specific and tell them to enter their "email address" instead of just "email" (no need to insinuate it when there's enough room in the toast 😂 )

Good idea!

**Review by gordonpn — APPROVED** [review]
Noice!

**Pull request merged**
