### PR TITLE
Add firebase hosting preview channel on PR

### LINKED ISSUE #55: Firebase Hosting preview channels
Add auto-deploy preview links for new PRs.

New Firebase feature!

https://firebase.googleblog.com/2020/10/preview-channels-firebase-hosting.html

### PR DESCRIPTION
**Pull request by sttic**
Resolves #55

### CODE REVIEW

**Comment by gordonpn** [comment]
Whoa, that's pretty cool! Feel free to ping me for a review :)

**Comment by sttic** [comment]
Sure thing, if I eventually get it working :joy: :joy: I'm not sure if it's user error on my side or bcs I'm using a pre-release v0.3-alpha action, but it's not authenticating the service account correctly atm :cry: 

Also I hope you didn't get notification spammed with the failed runs, and sorry if you did :sweat_smile:

**Comment by gordonpn** [comment]
> Also I hope you didn't get notification spammed with the failed runs, and sorry if you did 😅

Don't worry about that! hahahha

**Comment by sttic** [comment]
After so much troubleshooting leading to no where (even to the point of making an identical repo, using the same secrets, and it magically working on my personal one while this wasn't), I finally found out why it hasn't been working all this time.

The [action](https://github.com/FirebaseExtended/action-hosting-deploy) names the channel based on the pr number and branch name, which was too long, so it truncated it to `pr56-ci_firebase-preview-`. While the command mentions:

> Channel IDs can only include letters, numbers, underscores, hyphens, and periods

It ends up throwing an non-descriptive `Error: HTTP Error: 502, Unknown Error` error when trying to use either a hyphen or underscore as the **last** character.

:cry:

**Comment by gordonpn** [comment]
> After so much troubleshooting leading to no where (even to the point of making an identical repo, using the same secrets, and it magically working on my personal one while this wasn't), I finally found out why it hasn't been working all this time.
> 
> The [action](https://github.com/FirebaseExtended/action-hosting-deploy) names the channel based on the pr number and branch name, which was too long, so it truncated it to `pr56-ci_firebase-preview-`. While the command mentions:
> 
> > Channel IDs can only include letters, numbers, underscores, hyphens, and periods
> 
> It ends up throwing an non-descriptive `Error: HTTP Error: 502, Unknown Error` error when trying to use either a hyphen or underscore as the **last** character.
> 
> 😢

Omg, I can only imagine how you felt when you found that out. Amazing troubleshooting! Hahahah

**Pull request closed without merging**
