### PR TITLE
fix: content edits

### LINKED ISSUE #64: Clean up FAQ
some of the stuff is redundant

### PR DESCRIPTION
**Pull request by ellenli030**
Resolves #64

### CODE REVIEW

**Comment by ellenli030** [comment]
oop my formatter changed the tabbing in `data.ta`

**Comment by gordonpn** [comment]
@ellenli030 I pushed a commit to fix the formatting, hope you don't mind haha

**Review by gordonpn — COMMENTED** [review]
Loving the shorter FAQ section 😄

The use of emojis is fun too. 

One question:

Does the FAQ section subtitle make the last FAQ item redundant?

Screen Shot 2020-10-28 at 4 04 44 PM

**Comment by ellenli030** [comment]
> Loving the shorter FAQ section 😄
> 
> The use of emojis is fun too.
> 
> One question:
> 
> Does the FAQ section subtitle make the last FAQ item redundant?
> 
> Screen Shot 2020-10-28 at 4 04 44 PM
I was thinking that as well. The thing about having the subtitle is that we can link the email with a mailto, but since we're passing in the faq object as strings, im not sure if we can link it.

**Review by gordonpn — APPROVED** [review]

**Review by sttic — COMMENTED** [review]
Great changes! I think it'd be nice if the pricing tier cards were the same height when they're beside each other on desktop (the height changed with some of the rewording)

image

Maybe consider adding a min height on the pricing card on the desktop breakpoints or tweaking the width?

**Comment by ellenli030** [comment]
image

**Review by sttic — APPROVED** [review]

**Pull request merged**
